In [1]:
#BP神经网络
%matplotlib qt5
import os
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import Callback

Using TensorFlow backend.


In [2]:
from sklearn.preprocessing import scale

In [3]:
#训练数据
X = []
Y = []
Z = []
path = '/Users/liuyingjie/Downloads/data/data3/'
filenames = os.listdir(path)
indexs = []
for filename in filenames:
    indexs.append(int(filename))
indexs.sort()
#print(indexs)
for index in indexs:
    file_path = path + str(index)
    with open(file_path,'r',encoding='utf8') as f:
        lines=f.readlines()
    for num in range(34, 54):
        #print(lines[num])
        temps = lines[num].split()
        X.append(float(temps[2])/100)
        #print(float(temps[2])/100)
        Y.append(float(temps[3])/100)
        #print(float(temps[3])/100)
    for line in lines:
        temps = line.split()
        size = len(temps)
        if(size == 11 and temps[0] == '1000000'):
            #print(temps)
            Z.append(float(temps[1])*100000000)
            Z.append(float(temps[6])*100000000)
        if(size == 16 and temps[0] == '1000000'):
            #print(temps)
            Z.append(float(temps[1])*100000000)
            Z.append(float(temps[6])*100000000)
            Z.append(float(temps[11])*100000000)
            
for i in range(len(X)):
    print(Z[i])
            

22.916
28.301
34.407
40.397
44.97
46.156
43.445
38.134
31.779
26.049999999999997
21.038999999999998
17.147000000000002
28.247
36.756
47.825
60.607
70.708
73.54100000000001
67.27000000000001
55.769999999999996
43.005
33.077
25.451999999999998
19.928
34.417
47.884
67.96000000000001
95.923
123.98
134.07
113.73
83.964
59.047999999999995
41.818
30.374
22.878
40.876000000000005
60.426
95.557
159.63
253.05
291.83
214.39
130.26
79.106
51.188
35.149
25.451
44.949
70.637
124.24
253.18
588.23
837.2199999999999
418.46
186.33
97.48299999999999
58.335
38.412
27.076999999999998
46.123
73.621
133.44
292.09
838.8399999999999
1456.7
533.65
207.37
103.16
60.261
39.236
27.618
43.547000000000004
67.306
114.12
215.34999999999997
419.06
534.38
327.93
164.84
90.938
56.21
37.293
26.535999999999998
38.150999999999996
55.443000000000005
84.114
130.38
186.45000000000002
207.04999999999998
164.87
112.17
70.845
47.494
33.42
24.363000000000003
31.969
43.236
59.17
79.162
97.61399999999999
103.30999999999999
90.991
70

In [4]:
#预测数据
X_pred = []
Y_pred = []
Z_real = []
path = '/Users/liuyingjie/Downloads/data2/'
filenames = os.listdir(path)
indexs = []
for filename in filenames:
    indexs.append(int(filename))
indexs.sort()
for index in indexs:
    file_path = path + str(index)
    with open(file_path,'r',encoding='utf8') as f:
        lines=f.readlines()
    for num in range(34, 54):
        temps = lines[num].split()
        X_pred.append(float(temps[2])/100)
        Y_pred.append(float(temps[3])/100)
    for line in lines:
        temps = line.split()
        size = len(temps)
        if(size == 11 and temps[0] == '1000000'):
            Z_real.append(float(temps[1])*100000000)
            Z_real.append(float(temps[6])*100000000)
        if(size == 16 and temps[0] == '1000000'):
            Z_real.append(float(temps[1])*100000000)
            Z_real.append(float(temps[6])*100000000)
            Z_real.append(float(temps[11])*100000000)
            
for i in range(len(Z_real)):
    print(Z_real[i])

22.89
23.918
25.091
26.020000000000003
27.192999999999998
28.435
29.414
30.573999999999998
31.768
32.976
34.342
35.677
37.012
38.314
39.348
40.387
41.506
42.544
43.479
44.318
44.994
45.604
45.911
46.376000000000005
46.268
46.163
45.81
45.397
44.882999999999996
44.254
43.394
42.451
41.467
40.412
39.325
38.086
36.916000000000004
35.629999999999995
34.36
33.087
31.819000000000003
30.621
29.400000000000002
28.313000000000002
27.219
26.093
25.356
23.976000000000003
22.97
22.244
21.089000000000002
20.247
19.351
18.561999999999998
17.814999999999998
23.953999999999997
25.019
26.13
27.64
28.601
31.463
31.066
32.331
33.727
35.107
36.613
38.065
39.477
40.963
42.259
43.583
44.902
46.158
47.146
48.114
48.916
49.663000000000004
50.012
50.300999999999995
50.5
50.236
49.873
49.370000000000005
48.739000000000004
47.970000000000006
46.997
45.937999999999995
44.786
43.57
42.226
40.864
39.601
38.066
36.592999999999996
35.207
33.742000000000004
32.372
31.093
29.814
28.570999999999998
27.336000000000002
26

In [5]:
X_pred = scale(np.array(X_pred))
Y_pred = scale(np.array(Y_pred))
X_pred_ = np.array([X_pred,Y_pred])
Y_real = scale(np.array(Z_real))

In [6]:
import matplotlib.pyplot as plt  
from mpl_toolkits.mplot3d import Axes3D  

In [7]:
X = scale(np.array(X))
Y = scale(np.array(Y))
X_ = np.array([X,Y])

In [8]:
Y_ = scale(np.array(Z))
# X = [98+i/12 for i in range(48)]
# Y = [98+i/12 for i in range(48)]
# X, Y = np.meshgrid(X,Y)
# X = X.reshape(2304,)
# Y = Y.reshape(2304,)
# X = np.array(X)
# Y = np.array(Y)
# Y_ = [1/((X[i]-99.8)**2+(Y[i]-99.8)**2+.5) for i in range(2304)]
# Y_ = np.array(Y_)
# X = scale(X)
# Y = scale(Y)
# X_ = np.array([X,Y])

ax = plt.figure().add_subplot(111, projection = '3d')  
ax.scatter(X_[0], X_[1], Y_, c = 'b', marker = '.') #点为红色三角形   
ax.set_xlabel('X Label')  
ax.set_ylabel('Y Label')  
ax.set_zlabel('Z Label')  
plt.show()

In [20]:
X_.shape

(2, 140)

In [21]:
from keras.layers import Dense, Activation
#构建神经网络模型
model = Sequential()
model.add(Dense(units = 128, input_dim = 2))
model.add(Activation("relu"))
model.add(Dense(units = 128))
model.add(Activation("relu"))
model.add(Dense(units = 1))
model.add(Activation("linear"))
#构建编译模型
model.compile(loss='mean_squared_error', 
              optimizer='Adam', #Adam
              metrics=['mae'])
model.fit(X_.T, Y_.reshape((-1,1)), epochs = 100, batch_size = 10, shuffle=True, verbose = 1)

In [23]:
# 模型评估
loss_and_metrics = model.evaluate(X_.T, Y_, batch_size=100)
loss_and_metrics

140/140 [==============================] - 0s 298us/step


[0.0012921630571197187, 0.022824091304625784]

In [24]:
#预测
with open('error.txt','w',encoding='utf8') as f:
    Y_pred = model.predict(X_pred_.T)
    #error = np.subtract(Y_pred, Y_real)
    Y_real = Y_real.reshape(3020, 1)
    errors = (Y_pred - Y_real) / Y_real
    errors = abs(errors)
    errors.reshape(3020,1)
    print(errors)
    errors = errors.tolist()
    #print(error.reshape(1,3020))
    # error = np.divide(error, Y_real)
    # for e in error:
    #     if(e <= 0.1):
    #         print(e)
    #print(len(Y_pred))

    for error in errors:
            f.write(str(error))

[[0.35982176]
 [0.31905075]
 [0.27506717]
 ...
 [0.02336379]
 [0.02043331]
 [0.01826871]]


In [25]:
ax = plt.figure().add_subplot(111, projection = '3d')  
ax.scatter(X_pred_[0], X_pred_[1], Y_pred, c = 'b', marker = 'o') #点为红色三角形  
ax.scatter(X_pred_[0], X_pred_[1], Y_real, c = 'r', marker = '^', alpha=0.20)
ax.set_xlabel('X Label')  
ax.set_ylabel('Y Label')  
ax.set_zlabel('Z Label')  
plt.show()

In [60]:
print(Y_pred)

[[ -6.06070757e-01]
 [ -5.70661426e-01]
 [ -5.37736475e-01]
 [ -5.24983227e-01]
 [ -5.11090577e-01]
 [ -4.95574772e-01]
 [ -4.79608119e-01]
 [ -4.54751194e-01]
 [ -4.50733662e-01]
 [ -4.40949708e-01]
 [ -4.22420144e-01]
 [ -4.25342202e-01]
 [ -4.34590220e-01]
 [ -4.60256279e-01]
 [ -4.86478269e-01]
 [ -4.87018049e-01]
 [ -5.09039879e-01]
 [ -5.30557454e-01]
 [ -5.30808866e-01]
 [ -5.35952866e-01]
 [ -5.57508051e-01]
 [ -5.80280542e-01]
 [ -5.71201503e-01]
 [ -5.25325239e-01]
 [ -4.89915907e-01]
 [ -4.58722830e-01]
 [ -4.46672380e-01]
 [ -4.29320782e-01]
 [ -4.11134630e-01]
 [ -3.80735517e-01]
 [ -3.65119457e-01]
 [ -3.67205620e-01]
 [ -3.45412254e-01]
 [ -3.50948393e-01]
 [ -3.65163028e-01]
 [ -3.88764858e-01]
 [ -4.07924652e-01]
 [ -4.17289019e-01]
 [ -4.59604323e-01]
 [ -4.78423297e-01]
 [ -4.83282149e-01]
 [ -5.03735662e-01]
 [ -5.26508272e-01]
 [ -5.52506566e-01]
 [ -5.49966276e-01]
 [ -4.91083860e-01]
 [ -4.44579810e-01]
 [ -4.09170866e-01]
 [ -3.80207181e-01]
 [ -3.66414249e-01]


In [61]:
print(Y_real)

[[ -5.18606646e-01]
 [ -5.04089826e-01]
 [ -4.89373184e-01]
 [ -4.73689835e-01]
 [ -4.56661735e-01]
 [ -4.39217789e-01]
 [ -4.24052898e-01]
 [ -4.10243557e-01]
 [ -3.99496358e-01]
 [ -3.93598900e-01]
 [ -3.93534093e-01]
 [ -3.98389235e-01]
 [ -4.08164325e-01]
 [ -4.21255386e-01]
 [ -4.36863127e-01]
 [ -4.53664401e-01]
 [ -4.70525082e-01]
 [ -4.86532467e-01]
 [ -5.01222106e-01]
 [ -5.15495898e-01]
 [ -5.28424941e-01]
 [ -5.39771607e-01]
 [ -5.04721697e-01]
 [ -4.87839413e-01]
 [ -4.68429648e-01]
 [ -4.47599524e-01]
 [ -4.24538952e-01]
 [ -3.99523361e-01]
 [ -3.78023563e-01]
 [ -3.57069225e-01]
 [ -3.40683797e-01]
 [ -3.31762002e-01]
 [ -3.32226454e-01]
 [ -3.39263439e-01]
 [ -3.54206906e-01]
 [ -3.72957798e-01]
 [ -3.95343295e-01]
 [ -4.20051051e-01]
 [ -4.42636371e-01]
 [ -4.64152371e-01]
 [ -4.83383916e-01]
 [ -5.00741453e-01]
 [ -5.17180886e-01]
 [ -5.30536576e-01]
 [ -4.89837636e-01]
 [ -4.68715880e-01]
 [ -4.43721892e-01]
 [ -4.15293120e-01]
 [ -3.84212653e-01]
 [ -3.49060132e-01]


In [26]:
x = [1, 1, 1]
y = [2, 2, 2]
X = np.array(x)
Y = np.array(y)
err = X - Y / Y
print(err)

[0. 0. 0.]
